#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Sep  8 21:07:34 2010

import wx
from frame import IagnoFrame

class IagnoApp(wx.App):
    def OnInit(self):
        frame_1 = IagnoFrame(None, -1, "PyIango")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = IagnoApp(0)
    app.MainLoop()
